package pl.stophazard.app

object BlockedDomains {
    private val domains = setOf(
        "bet365.com", "betway.com", "williamhill.com", "888.com",
        "pokerstars.com", "unibet.com", "bwin.com", "ladbrokes.com",
        "coral.co.uk", "skybet.com", "casino.com", "leovegas.com",
        "betfair.com", "wincasino.io", "win-casino.io", "wincasino.com",
        "casino1.com", "tikalcasino.com",
        "sts.pl", "fortuna.pl", "superbet.pl", "betters.pl",
        "betfan.pl", "etoto.pl", "lvbet.pl", "forbet.pl",
        "totalbet.pl", "01bet.com", "22bet.com", "1xbet.com",
        "melbet.com", "mostbet.com", "betcris.com"
        "stake.com",
        "stake.bet",
        "bet365.co.uk",
        "bet365.com.au",
        "bet365.es",
        "betclic.fr",
        "betclic.pl",
        "betway.com",
        "1xbet.pl",
        "melbet.pl",
        "mostbet.pl",
        "22bet.pl",
        "parimatch.com",
        "pokerstars.eu",
        "pokerstarscasino.com",
        "ggpoker.com",
        "casino777.com",
        "casino-x.com",
        "rabona.com",
        "22bet.com",
        "betonline.ag",
        "draftkings.com",
        "fanduel.com",
        "betsson.com",
        "mrgreen.com",
        "casumo.com",
        "bet-at-home.com",
        "10bet.com",
        "bet9ja.com",
        "betway.pl",
        "totalbet.pl",
        "e-toto.pl",
        "etoto.pl",
        "bet365.dk",
        "bet365.de",
        "bet365.gr",
        "bet365.it",
        "bet365.ro",
        "bet365.pt",
        "bet365.mx",
        "bet365.in",
        "bet365.ca",
        "bet365.co.za",
        "betclic.com",
        "betclic.pt",
        "betclic.es",
        "betclic.it",
        "betclic.ro",
        "betway.co.uk",
        "betway.de",
        "betway.es",
        "betway.it",
        "betway.fr",
        "unibet.co.uk",
        "unibet.fr",
        "unibet.be",
        "unibet.dk",
        "unibet.se",
        "unibet.nl",
        "unibet.ie",
        "bwin.de",
        "bwin.fr",
        "bwin.es",
        "bwin.it",
        "bwin.gr",
        "bwin.ro",
        "betfair.co.uk",
        "betfair.es",
        "betfair.it",
        "betsson.es",
        "betsson.se",
        "betsson.dk",
        "betsson.no",
        "betsson.fi",
        "betsson.gr",
        "nordicbet.com",
        "racebets.com",
        "bet-at-home.de",
        "10bet.co.uk",
        "marathonbet.com",
        "marathonbet.co.uk",
        "betonline.com",
        "betnow.eu",
        "parimatch.co.uk",
        "22bet.co.uk",
        "melbet.co.uk",
        "mostbet.co.uk",
        "1xstavka.ru",
        "1xbet.co.uk",
        "1xbet.ng",
        "pin-up.bet",
        "pinup.bet",
        "pin-up.ru",
        "vulkanvegas.com",
        "vulkan.bet",
        "joycasino.com",
        "casinozer.com",
        "williamhill.co.uk",
        "paddy-power.com",
        "paddypower.com",
        "boylesports.com",
        "betvictor.com",
        "betfred.com",
        "888casino.com",
        "888sport.com",
        "888poker.com",
        "partypoker.com",
        "partypoker.eu",
        "betmaster.com",
        "betmaster.io",
        "linebet.com",
        "betwinner.com",
        "betwinner1.com",
        "betwinner.ru",
        "bettilt.com",
        "betboro.com",
        "sportingbet.com",
        "sportingbet.co.uk",
        "betdaq.com",
        "betregal.com",
        "betus.com",
        "mybookie.ag",
        "bovada.lv",
        "bovada.com",
        "betmgm.com",
        "caesars.com",
        "pointsbet.com",
        "betrivers.com",
        "hardrock.bet",
        "bwin.pl",
        "betsson.pl",
        "01bet.pl",
    )

    fun domains(): Set<String> = domains

    fun normalize(host: String): String =
        host.lowercase().trim().trimEnd('.').removePrefix("www.")

    fun isBlocked(host: String): Boolean {
        val normalized = normalize(host)
        return domains.any { normalized == it || normalized.endsWith(".$it") }
    }

    fun decision(host: String): BlockDecision =
        if (isBlocked(host)) BlockDecision.BLOCK else BlockDecision.ALLOW
}

enum class BlockDecision { BLOCK, ALLOW }
