package pl.stophazard.app

object BlockedDomains {
    private val domains = setOf(
        "bet365.com",
        "betway.com",
        "williamhill.com",
        "888.com",
        "pokerstars.com",
        "unibet.com",
        "bwin.com",
        "ladbrokes.com",
        "coral.co.uk",
        "skybet.com",
        "casino.com",
        "leovegas.com",
        "betfair.com",
        "wincasino.io",
        "win-casino.io",
        "wincasino.com",
        "casino1.com",
        "tikalcasino.com",
        "sts.pl",
        "fortuna.pl",
        "superbet.pl",
        "betters.pl",
        "betfan.pl",
        "etoto.pl",
        "lvbet.pl",
        "forbet.pl",
        "totalbet.pl",
        "01bet.com",
        "22bet.com",
        "1xbet.com",
        "melbet.com",
        "mostbet.com",
        "betcris.com",
        "stake.com",
        "stake.bet",
        "bet365.co.uk",
        "bet365.com.au",
        "bet365.es",
        "betclic.fr",
        "betclic.pl",
        "betway.pl",
        "888casino.com",
        "888sport.com",
        "pokerstars.eu",
        "pokerstarscasino.com",
        "ggpoker.com",
        "partypoker.com",
        "casino777.com",
        "casino-x.com",
        "rabona.com",
        "betmaster.com",
        "betmaster.io",
        "vulkanvegas.com",
        "vulkan.bet",
        "joycasino.com",
        "casumo.com",
        "mrgreen.com",
        "bet-at-home.com",
        "10bet.com",
        "marathonbet.com",
        "parimatch.com",
        "pin-up.bet",
        "pinup.com",
        "betwinner.com",
        "linebet.com",
        "1win.com",
        "1xbit.com",
        "rollbit.com",
        "roobet.com",
        "bc.game",
        "cloudbet.com",
        "bet9ja.com",
        "sportingbet.com",
        "betvictor.com",
        "betfred.com",
        "paddypower.com",
        "virginbet.com",
        "virgingames.com",
        "superbet.com",
        "betsson.com",
        "nordicbet.com",
        "betsafe.com",
        "betonline.ag",
        "bovada.lv",
        "mybookie.ag",
        "draftkings.com",
        "fanduel.com",
        "betmgm.com",
        "betrivers.com",
        "hardrock.bet",
        "pointsbet.com",
        "caesars.com",
    )

    fun domains(): Set<String> = domains

    fun normalize(host: String): String =
        host.lowercase().trim().trimEnd('.').removePrefix("www.")

    fun isBlocked(host: String): Boolean {
        val normalized = normalize(host)
        return domains.any { normalized == it || normalized.endsWith(".$it") }
    }

    fun decision(host: String): BlockDecision =
        if (isBlocked(host)) BlockDecision.BLOCK else BlockDecision.ALLOW
}

enum class BlockDecision { BLOCK, ALLOW }
