const state={domains:JSON.parse(localStorage.getItem("stopHazardDomains")||"[]"),enabled:localStorage.getItem("stopHazardEnabled")!=="0",blocked:Number(localStorage.getItem("stopHazardBlocked")||1284)};const $=id=>document.getElementById(id);
function renderDomains(){const list=$("domainList");if(!list)return;list.innerHTML="";state.domains.forEach((domain,i)=>{const row=document.createElement("div");row.className="domain";row.innerHTML="<span>"+escapeHtml(domain)+"</span><button>Usuń</button>";row.querySelector("button").onclick=()=>{state.domains.splice(i,1);save();renderDomains()};list.appendChild(row)});$("domainCount").textContent=state.domains.length;$("domains").textContent=8+state.domains.length}
function escapeHtml(v){return String(v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function save(){localStorage.setItem("stopHazardDomains",JSON.stringify(state.domains));localStorage.setItem("stopHazardEnabled",state.enabled?"1":"0");localStorage.setItem("stopHazardBlocked",String(state.blocked))}
function setProtection(enabled){state.enabled=enabled;save();$("toggle").classList.toggle("on",enabled);document.querySelector(".hero strong").textContent=enabled?"OCHRONA AKTYWNA":"OCHRONA WYŁĄCZONA";document.querySelector(".hero p").textContent=enabled?"Urządzenie jest chronione":"Ochrona jest obecnie wyłączona";document.querySelector(".status-dot").style.background=enabled?"#55e77d":"#777"}
if($("toggle"))$("toggle").onclick=()=>setProtection(!state.enabled);
if($("addDomain"))$("addDomain").onclick=()=>{const input=$("domainInput"),domain=input.value.trim().toLowerCase().replace(/^https?:\/\//,"").replace(/^www\./,"").split("/")[0];if(!/^(?=.{1,253}$)([a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?)(\.[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?)+$/.test(domain)){alert("Wpisz poprawną domenę.");return}if(!state.domains.includes(domain))state.domains.push(domain);input.value="";save();renderDomains()};
if($("domainInput"))$("domainInput").addEventListener("keydown",e=>{if(e.key==="Enter")$("addDomain").click()});
if($("clear"))$("clear").onclick=()=>{$("activity").innerHTML="<div class='activity-row'><span class='ok'>✓</span><div><b>Brak nowej aktywności</b><small>Historia została wyczyszczona</small></div></div>"};
if($("plans"))$("plans").onclick=()=>alert("Premium jest przygotowane jako moduł demonstracyjny.");
if($("navActivity"))$("navActivity").onclick=()=>location.href="activity.html";
if($("navSettings"))$("navSettings").onclick=()=>location.href="settings.html";
if($("blocked"))$("blocked").textContent=state.blocked.toLocaleString("pl-PL");
renderDomains();setProtection(state.enabled);